version: "3.9"
name: xazna-ai

services:
  nginx:
    image: nginx:alpine
    container_name: xazna_proxy
    restart: always
    ports:
      - "2102:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx_net
    depends_on:
      - server
      - client
      - docs

  postgres:
    image: postgres:15
    container_name: xazna_postgres
    restart: always
    env_file:
      - server/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - nginx_net

  redis:
    image: redis:7-alpine
    container_name: xazna_redis
    restart: always
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    networks:
      - nginx_net

  server:
    image: xazna_server:latest
    container_name: xazna_server
    restart: always
    env_file:
      - server/.env
    ports:
      - "8100:8100"
    volumes:
      - ./server/media-files:/app/media-files
      - /mnt/data04/web/Shakhriyor/backups/xazna:/app/backups
    depends_on:
      - postgres
      - redis
    networks:
      - nginx_net

  client:
    image: xazna_client:latest
    container_name: xazna_client
    restart: always
    env_file:
      - client/.env
    networks:
      - nginx_net

  docs:
    image: xazna_docs:latest
    container_name: xazna_docs
    ports:
      - "3101:3101"
    restart: always
    networks:
      - nginx_net

volumes:
  pg_data:

networks:
  nginx_net:
    name: nginx_net
    driver: bridge
